packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

injectWorkspacePackages: true
minimumReleaseAgeExclude:
  - prettier@3.9.5
syncInjectedDepsAfterScripts:
  - build
